# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2085f575a8aed78dc39a7dbd5508fa89dc4c99428ce3898b5818c1dc3d54e627b8f0044ea9ed1438583ba13233a822c4ec8176577b0d9f52a7610f8fbb5d086d

test:
  secret_key_base: db9d7f210cf792a7d8917e7c4fb9bedc936fc6031632855d0c8064df1dae0e08380a0d73e4571e1fa36072bb9d462594b4d68592d9070af1929b34e752b0582d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
